# Generated by Django 2.0.5 on 2018-08-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180821_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='User',
            new_name='user',
        ),
    ]
